const fs = require('fs');

const code = fs.readFileSync('data/catalog.ts', 'utf8');
const match = code.match(/export const PRODUCTS: Product\[\] = (\[[\s\S]*?\n\];)/);
const prods = JSON.parse(match[1].slice(0, -1));

const additionalWomenProducts = [
  // ETHNIC WEAR
  {
    id: 'w-eth-1',
    brand: 'Vasavi',
    title: 'Pure Chanderi Silk Hand-Block Anarkali Kurta Set with Dupatta',
    price: 2499,
    originalPrice: 4999,
    discountPercentage: 50,
    gender: 'women',
    category: 'ethnic',
    subCategory: 'anarkali sets',
    images: ['/assets/real/women/asset_62_brand_vasavi_vs076_s_1.jpg'],
    thumbnail: '/assets/real/women/asset_62_brand_vasavi_vs076_s_1.jpg',
    description: 'Authentic festive Chanderi silk anarkali kurta set featuring intricate zari embroidery and hand-block floral motifs.',
    fabric: 'Chanderi Silk',
    fit: 'Flared Regular Fit',
    rating: 4.9,
    reviewsCount: 312,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "Festive Bestseller",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-eth-2',
    brand: 'Divena',
    title: 'Floral Print Cotton Anarkali Suit Set with Organza Dupatta',
    price: 1899,
    originalPrice: 3799,
    discountPercentage: 50,
    gender: 'women',
    category: 'ethnic',
    subCategory: 'suit sets',
    images: ['/assets/real/women/asset_63_brand_divena_mmf0693-38_1.jpg'],
    thumbnail: '/assets/real/women/asset_63_brand_divena_mmf0693-38_1.jpg',
    description: 'Breezy pure cotton flared anarkali suit set with hand-block print and lightweight scalloped organza dupatta.',
    fabric: '100% Pure Cotton',
    fit: 'Flared Fit',
    rating: 4.8,
    reviewsCount: 184,
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "Garba Special",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-eth-3',
    brand: 'Pink Fort',
    title: 'Pastel Lavender Embroidered Raw Silk Kurta Palazzo Set',
    price: 3299,
    originalPrice: 5999,
    discountPercentage: 45,
    gender: 'women',
    category: 'ethnic',
    subCategory: 'kurta palazzo sets',
    images: ['/assets/real/women/asset_107_catalog_ingestion_pixyle_input_101790c1aa69d43650465fdd71ed22a1a7d251427b181416dd5127ffd9c060d3.jpg'],
    thumbnail: '/assets/real/women/asset_107_catalog_ingestion_pixyle_input_101790c1aa69d43650465fdd71ed22a1a7d251427b181416dd5127ffd9c060d3.jpg',
    description: 'Regal raw silk kurta with resham and gota patti embellishments paired with matching straight palazzo pants.',
    fabric: 'Raw Silk Blend',
    fit: 'Straight Relaxed Fit',
    rating: 4.9,
    reviewsCount: 220,
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "Designer Drop",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-eth-4',
    brand: 'KALKI',
    title: 'Champagne Gold Embellished Ready-to-Wear Georgette Saree',
    price: 4999,
    originalPrice: 8999,
    discountPercentage: 44,
    gender: 'women',
    category: 'ethnic',
    subCategory: 'sarees',
    images: ['/assets/real/cat_women_sub_sarees.webp'],
    thumbnail: '/assets/real/cat_women_sub_sarees.webp',
    description: 'Pre-draped festive georgette saree featuring shimmering sequin work with matching sleeveless designer blouse.',
    fabric: 'Georgette Silk',
    fit: 'Pre-stitched Drape',
    rating: 4.9,
    reviewsCount: 421,
    sizes: ['Free Size'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "Celebrity Pick",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-eth-5',
    brand: 'trueBrowns',
    title: 'Emerald Green Velvet Kurta Set with Silk Pants',
    price: 3450,
    originalPrice: 6900,
    discountPercentage: 50,
    gender: 'women',
    category: 'ethnic',
    subCategory: 'velvet sets',
    images: ['/assets/real/cat_women_sub_suits.webp'],
    thumbnail: '/assets/real/cat_women_sub_suits.webp',
    description: 'Luxurious micro-velvet straight kurta paired with pure silk trousers and hand-embroidered contrast dupatta.',
    fabric: 'Micro Velvet',
    fit: 'Comfort Fit',
    rating: 4.8,
    reviewsCount: 156,
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "Winter Festive",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },

  // DRESSES
  {
    id: 'w-dr-1',
    brand: 'Tequila',
    title: 'Midnight Black Halter Neck Slinky Maxi Slip Dress',
    price: 1799,
    originalPrice: 3299,
    discountPercentage: 45,
    gender: 'women',
    category: 'dresses',
    subCategory: 'party dresses',
    images: ['/assets/real/cat_women_dresses_card.png'],
    thumbnail: '/assets/real/cat_women_dresses_card.png',
    description: 'Chic bodycon halter neck slip dress cut from liquid satin fabric with a high side-slit for party nights.',
    fabric: 'Satin Elastane',
    fit: 'Slim Fit',
    rating: 4.9,
    reviewsCount: 268,
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "Club Night Iconic",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-dr-2',
    brand: 'Pink Fort',
    title: 'Royal Purple Silk A-Line Sleeveless Midi Dress',
    price: 2199,
    originalPrice: 4299,
    discountPercentage: 49,
    gender: 'women',
    category: 'dresses',
    subCategory: 'midi dresses',
    images: ['/assets/real/lookbook_women_5_pinkfort.webp'],
    thumbnail: '/assets/real/lookbook_women_5_pinkfort.webp',
    description: 'Minimalist statement jewel-toned A-line dress in raw silk with piped vertical details and back zip closure.',
    fabric: 'Raw Silk Blend',
    fit: 'A-Line Fit',
    rating: 4.8,
    reviewsCount: 174,
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "Trending Now",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-dr-3',
    brand: 'The Souled Store',
    title: 'Powerpuff Girls Varsity Bomber Dress - Limited Edition',
    price: 1899,
    originalPrice: 2899,
    discountPercentage: 34,
    gender: 'women',
    category: 'dresses',
    subCategory: 'casual dresses',
    images: ['/assets/real/lookbook_women_4_souledstore.webp'],
    thumbnail: '/assets/real/lookbook_women_4_souledstore.webp',
    description: 'Cozy relaxed streetwear varsity oversized dress with iconic 90s nostalgia graphic embroidery.',
    fabric: 'Heavyweight French Terry',
    fit: 'Relaxed Fit',
    rating: 4.9,
    reviewsCount: 520,
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "Buy 1 Get 1",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-dr-4',
    brand: 'Sassafras',
    title: 'Sage Green Ribbed Button-Down Knit Bodycon Dress',
    price: 1199,
    originalPrice: 2399,
    discountPercentage: 50,
    gender: 'women',
    category: 'dresses',
    subCategory: 'knit dresses',
    images: ['/assets/real/cat_women_sub_sweaters.webp'],
    thumbnail: '/assets/real/cat_women_sub_sweaters.webp',
    description: 'Soft stretchy fine-knit midi dress with mock collar and tortoiseshell front buttons.',
    fabric: 'Viscose Ribbed Knit',
    fit: 'Bodycon Fit',
    rating: 4.7,
    reviewsCount: 198,
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "Best Value",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },

  // BOTTOM WEAR
  {
    id: 'w-bt-1',
    brand: 'Tilt',
    title: 'Butter Soft Bamboo Wide-Leg High-Waist Relaxed Trousers',
    price: 1499,
    originalPrice: 2499,
    discountPercentage: 40,
    gender: 'women',
    category: 'bottom',
    subCategory: 'wide leg trousers',
    images: ['/assets/real/cat_women_bottom_card.png'],
    thumbnail: '/assets/real/cat_women_bottom_card.png',
    description: 'Breathable ultra-luxe bamboo cotton relaxed wide-leg trousers designed for effortlessly chic street outings.',
    fabric: 'Bamboo Spandex',
    fit: 'Wide Leg Loose Fit',
    rating: 4.9,
    reviewsCount: 341,
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "Bamboo Comfort",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-bt-2',
    brand: 'Chkokko',
    title: 'High-Waist Core Sculpt Seamless Activewear Leggings',
    price: 999,
    originalPrice: 1999,
    discountPercentage: 50,
    gender: 'women',
    category: 'bottom',
    subCategory: 'activewear',
    images: ['/assets/real/cat_women_sub_pyjamas.webp'],
    thumbnail: '/assets/real/cat_women_sub_pyjamas.webp',
    description: 'Squat-proof compression four-way stretch leggings with seamless tummy control ribbed waistband.',
    fabric: 'Nylon Spandex Blend',
    fit: 'Compression Fit',
    rating: 4.8,
    reviewsCount: 412,
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "Gym & Chill",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },

  // FOOT WEAR
  {
    id: 'w-ft-1',
    brand: 'CHUPPS',
    title: 'Cloud Foam Strappy Platform Slides - Coral Pink',
    price: 899,
    originalPrice: 1499,
    discountPercentage: 40,
    gender: 'women',
    category: 'footwear',
    subCategory: 'slides & sandals',
    images: ['/assets/real/cat_women_footwear_card.png'],
    thumbnail: '/assets/real/cat_women_footwear_card.png',
    description: 'Ultra-lightweight shock absorbing cloud foam platform slides with ergonomic arch support.',
    fabric: 'EVA Foam',
    fit: 'True to Size',
    rating: 4.9,
    reviewsCount: 388,
    sizes: ['UK 4', 'UK 5', 'UK 6', 'UK 7'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "60-Min Express",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-ft-2',
    brand: 'Ludic',
    title: 'Retro Classic Chunky Court Sneakers - Pastel White & Lilac',
    price: 1999,
    originalPrice: 3499,
    discountPercentage: 43,
    gender: 'women',
    category: 'footwear',
    subCategory: 'sneakers',
    images: ['/assets/real/cat_footwear.webp'],
    thumbnail: '/assets/real/cat_footwear.webp',
    description: 'Everyday street chunky court sneakers with cushioned memory foam insole and durable rubber cupsole.',
    fabric: 'Vegan Leather',
    fit: 'Regular Fit',
    rating: 4.8,
    reviewsCount: 275,
    sizes: ['UK 4', 'UK 5', 'UK 6', 'UK 7'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "Street Drop",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },

  // ACCESSORIES / BAGS / JEWELLERY
  {
    id: 'w-acc-1',
    brand: 'MyWishBag',
    title: 'Glitzy Pearl Encrusted Evening Box Clutch with Gold Chain',
    price: 1299,
    originalPrice: 2599,
    discountPercentage: 50,
    gender: 'women',
    category: 'accessories',
    subCategory: 'clutches & bags',
    images: ['/assets/real/women/asset_108_brand_mywishbag_61050895_1.jpg'],
    thumbnail: '/assets/real/women/asset_108_brand_mywishbag_61050895_1.jpg',
    description: 'Opulent faux pearl and crystal encrusted structured hardcase box clutch featuring detachable gold snake chain.',
    fabric: 'Metal & Faux Pearl',
    fit: 'Standard Clutch',
    rating: 4.9,
    reviewsCount: 165,
    sizes: ['Free Size'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "Wedding Glam",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-acc-2',
    brand: 'GIVA',
    title: 'Sterling Silver 925 Sparkling Zircon Halo Stud Earrings',
    price: 1199,
    originalPrice: 2199,
    discountPercentage: 45,
    gender: 'women',
    category: 'accessories',
    subCategory: 'fine jewellery',
    images: ['/assets/real/cat_women_sub_jewellery.webp'],
    thumbnail: '/assets/real/cat_women_sub_jewellery.webp',
    description: 'Hypoallergenic authentic 925 sterling silver stud earrings with rhodium anti-tarnish e-coating.',
    fabric: '925 Sterling Silver',
    fit: 'Studs',
    rating: 4.9,
    reviewsCount: 489,
    sizes: ['Free Size'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: "Certified 925",
    couponPromo: 'Coupon: KNOTFESTIVE999'
  }
];

const merged = [...prods, ...additionalWomenProducts];
console.log('Merged count:', merged.length);

// Replace in catalog.ts
const newCode = code.replace(
  /export const PRODUCTS: Product\[\] = \[[\s\S]*?\n\];/,
  'export const PRODUCTS: Product[] = ' + JSON.stringify(merged, null, 2) + ';'
);

fs.writeFileSync('data/catalog.ts', newCode, 'utf8');
console.log('Successfully updated data/catalog.ts with authentic women products!');
