const fs = require('fs');

const code = fs.readFileSync('data/catalog.ts', 'utf8');
const match = code.match(/export const PRODUCTS: Product\[\] = (\[[\s\S]*?\n\];)/);
const prods = JSON.parse(match[1].slice(0, -1));

const menBrands = new Set([
  'SNITCH', 'The Indian Garage Co', 'The Bear House', 'Thomas Scott', 'Powerlook',
  'Javinishka', 'Manyavar', 'TASVA', 'Banana Club', 'OneMile', 'BLUE TYGA', 'Smokeshow',
  'The Kurta Studio', 'Hancock', 'Bene Kleed', 'Rawayi', 'Vastramay', 'BlueJam', 'XKIND',
  'FOUL CHILD', 'DL Street', 'Veirdo', 'WEEZY', 'CALDRI', 'CHUPPS', 'Lotto', 'Bersache',
  'Ten x You by Sachin Tendulkar', 'FREECULTR', 'musclemind', 'Aldeno', 'Uri', 'JONESBURG',
  'Rustlines', 'WHAT THE FLEX', 'Rigo', 'Mint & Oak', 'Supersox', 'Aesthetic Nation',
  'The Gray Clothing', 'Fraganote', 'Salty Alpha', 'French Accent', 'Project Shades', 'AUTHENTICS',
  'MyDesignation', 'Chapter 2', 'Bewakoof'
]);

// Extract non-w products and tag strictly
const cleanedOtherProds = prods.filter(p => !p.id.startsWith('w-')).map(p => {
  const brand = p.brand || '';
  const title = (p.title || '').toLowerCase();
  if (menBrands.has(brand) || title.includes("men's") || title.includes("men ") || title.includes("for men")) {
    return { ...p, gender: 'men' };
  }
  if (brand === 'Chumbak') {
    return { ...p, gender: 'women', category: 'accessories', subCategory: 'home decor & lifestyle' };
  }
  if (brand === 'trueBrowns') {
    return { ...p, gender: 'women', category: 'ethnic' };
  }
  if (brand === 'GIVA') {
    return { ...p, gender: 'women', category: 'accessories' };
  }
  if (brand === 'Cava Athleisure') {
    return { ...p, gender: 'women', category: 'bottom' };
  }
  return { ...p, gender: 'men' };
});

// The 24 pure women fashion items
const pureWomenProducts = [
  // --- ETHNIC WEAR ---
  {
    id: 'w-eth-1',
    brand: 'Pink Fort',
    title: 'Mustard Yellow Embroidered Chanderi Kurta Set',
    price: 2699,
    originalPrice: 4999,
    discountPercentage: 46,
    gender: 'women',
    category: 'ethnic',
    subCategory: 'kurta sets',
    images: ['/assets/real/women/asset_107_catalog_ingestion_pixyle_input_101790c1aa69d43650465fdd71ed22a1a7d251427b181416dd5127ffd9c060d3.jpg'],
    thumbnail: '/assets/real/women/asset_107_catalog_ingestion_pixyle_input_101790c1aa69d43650465fdd71ed22a1a7d251427b181416dd5127ffd9c060d3.jpg',
    description: 'Festive pure Chanderi silk kurta with delicate white resham floral embroidery paired with matching cigarette trousers.',
    fabric: 'Chanderi Silk',
    fit: 'Regular Straight Fit',
    rating: 4.9,
    reviewsCount: 312,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Festive Bestseller',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-eth-2',
    brand: 'Vasavi',
    title: 'Desi Baddie Festive Garba Lehenga Choli Set',
    price: 3999,
    originalPrice: 7999,
    discountPercentage: 50,
    gender: 'women',
    category: 'ethnic',
    subCategory: 'lehenga choli',
    images: ['/assets/real/lookbook_women_2_desibaddie.webp'],
    thumbnail: '/assets/real/lookbook_women_2_desibaddie.webp',
    description: 'Statement festive magenta & parakeet green flared lehenga choli with ornate mirrorwork border and mirror embellished dupatta.',
    fabric: 'Georgette Silk',
    fit: 'Flared Fit',
    rating: 4.9,
    reviewsCount: 450,
    sizes: ['S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Garba Special',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-eth-3',
    brand: 'Pink Fort',
    title: 'Blush Pink Silk Anarkali Gown with Embroidered Cape',
    price: 2899,
    originalPrice: 5499,
    discountPercentage: 47,
    gender: 'women',
    category: 'ethnic',
    subCategory: 'anarkalis',
    images: ['/assets/real/cat_women_ethnic_card.png'],
    thumbnail: '/assets/real/cat_women_ethnic_card.png',
    description: 'Floor-length pure mulmul silk anarkali with delicate scalloped borders and matching organza dupatta.',
    fabric: 'Mulmul Silk',
    fit: 'Flared Fit',
    rating: 4.8,
    reviewsCount: 219,
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Dandiya Drops',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-eth-4',
    brand: 'KALKI',
    title: 'Champagne Gold Embellished Ready-to-Wear Georgette Saree',
    price: 4999,
    originalPrice: 8999,
    discountPercentage: 44,
    gender: 'women',
    category: 'ethnic',
    subCategory: 'sarees',
    images: ['/assets/real/cat_women_sub_sarees.webp'],
    thumbnail: '/assets/real/cat_women_sub_sarees.webp',
    description: 'Pre-draped festive georgette saree featuring shimmering sequin work with matching sleeveless designer blouse.',
    fabric: 'Georgette Silk',
    fit: 'Pre-stitched Drape',
    rating: 4.9,
    reviewsCount: 421,
    sizes: ['Free Size'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Celebrity Pick',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-eth-5',
    brand: 'trueBrowns',
    title: 'Ivory Floral Embroidered Salwar Kameez Suit Set',
    price: 2450,
    originalPrice: 4900,
    discountPercentage: 50,
    gender: 'women',
    category: 'ethnic',
    subCategory: 'suit sets',
    images: ['/assets/real/cat_women_sub_suits.webp'],
    thumbnail: '/assets/real/cat_women_sub_suits.webp',
    description: 'Timeless handloom cotton silk kurta suit set with intricate pearl thread work and tapered churidar pants.',
    fabric: 'Cotton Silk',
    fit: 'Comfort Regular Fit',
    rating: 4.8,
    reviewsCount: 165,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Classic Grace',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-eth-6',
    brand: 'Pink Fort',
    title: 'Cream Zari Work Designer Kurta Sharara Set',
    price: 3199,
    originalPrice: 5999,
    discountPercentage: 46,
    gender: 'women',
    category: 'ethnic',
    subCategory: 'sharara sets',
    images: ['/assets/real/cat_women_sub_kurtas.webp'],
    thumbnail: '/assets/real/cat_women_sub_kurtas.webp',
    description: 'Tiered flared sharara set cut from soft viscose silk featuring antique gold zari work and scalloped hemlines.',
    fabric: 'Viscose Silk',
    fit: 'Flared Fit',
    rating: 4.9,
    reviewsCount: 198,
    sizes: ['S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Diwali Special',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },

  // --- DRESSES ---
  {
    id: 'w-dr-1',
    brand: 'Pink Fort',
    title: 'Royal Purple Silk A-Line Sleeveless Midi Dress',
    price: 2199,
    originalPrice: 4299,
    discountPercentage: 49,
    gender: 'women',
    category: 'dresses',
    subCategory: 'midi dresses',
    images: ['/assets/real/lookbook_women_5_pinkfort.webp'],
    thumbnail: '/assets/real/lookbook_women_5_pinkfort.webp',
    description: 'Minimalist statement jewel-toned A-line dress in raw silk with piped vertical details and back zip closure.',
    fabric: 'Raw Silk Blend',
    fit: 'A-Line Fit',
    rating: 4.8,
    reviewsCount: 174,
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Trending Now',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-dr-2',
    brand: 'The Souled Store',
    title: 'Powerpuff Girls 1998 Varsity Bomber Dress - Limited Drop',
    price: 1899,
    originalPrice: 2899,
    discountPercentage: 34,
    gender: 'women',
    category: 'dresses',
    subCategory: 'street dresses',
    images: ['/assets/real/lookbook_women_4_souledstore.webp'],
    thumbnail: '/assets/real/lookbook_women_4_souledstore.webp',
    description: 'Cozy relaxed streetwear varsity oversized dress with iconic 90s nostalgia graphic embroidery.',
    fabric: 'Heavyweight French Terry',
    fit: 'Relaxed Fit',
    rating: 4.9,
    reviewsCount: 520,
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Buy 1 Get 1',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-dr-3',
    brand: 'Tequila',
    title: 'Midnight Black Halter Neck Slinky Maxi Slip Dress',
    price: 1999,
    originalPrice: 3499,
    discountPercentage: 43,
    gender: 'women',
    category: 'dresses',
    subCategory: 'party dresses',
    images: ['/assets/real/lookbook_women_7_tequila.webp'],
    thumbnail: '/assets/real/lookbook_women_7_tequila.webp',
    description: 'Chic bodycon halter neck slip dress cut from liquid satin fabric with a high side-slit for party nights.',
    fabric: 'Satin Elastane',
    fit: 'Slim Fit',
    rating: 4.9,
    reviewsCount: 268,
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Dress Like a Shot',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-dr-4',
    brand: 'Sassafras',
    title: 'Classic White Pleated Fit & Flare Midi Dress',
    price: 1299,
    originalPrice: 2499,
    discountPercentage: 48,
    gender: 'women',
    category: 'dresses',
    subCategory: 'day dresses',
    images: ['/assets/real/cat_women_dresses_card.png'],
    thumbnail: '/assets/real/cat_women_dresses_card.png',
    description: 'Breezy white skater dress with sweetheart neckline and fitted bodice made for brunch and summer getaways.',
    fabric: 'Cotton Poplin',
    fit: 'Fit & Flare',
    rating: 4.8,
    reviewsCount: 195,
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Day Outing Pick',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },

  // --- TOPS & TEES ---
  {
    id: 'w-tp-1',
    brand: 'Chkokko',
    title: 'Sky Blue "One More Rep" Athletic Training Crop Tee',
    price: 699,
    originalPrice: 1399,
    discountPercentage: 50,
    gender: 'women',
    category: 'top',
    subCategory: 'activewear tops',
    images: ['/assets/real/lookbook_women_3_chkokko.webp'],
    thumbnail: '/assets/real/lookbook_women_3_chkokko.webp',
    description: 'Moisture-wicking breathable dry-fit athletic crop t-shirt engineered for workouts, running and casual street style.',
    fabric: 'Quick-Dry Poly Spandex',
    fit: 'Athletic Regular Fit',
    rating: 4.9,
    reviewsCount: 380,
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Buy 2 Get 5% Off',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-tp-2',
    brand: 'Chkokko',
    title: 'Chic Seamless Black Strappy Tube Corset Top',
    price: 799,
    originalPrice: 1599,
    discountPercentage: 50,
    gender: 'women',
    category: 'top',
    subCategory: 'corsets',
    images: ['/assets/real/women/asset_108_brand_mywishbag_61050895_1.jpg'],
    thumbnail: '/assets/real/women/asset_108_brand_mywishbag_61050895_1.jpg',
    description: 'Double-lined premium ribbed stretch bandeau tube top with built-in silicone grip for all-day non-slip hold.',
    fabric: 'Ribbed Cotton Elastane',
    fit: 'Fitted Bodycon',
    rating: 4.8,
    reviewsCount: 290,
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Wardrobe Essential',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-tp-3',
    brand: 'नी',
    title: 'Azure Blue Hand-Block Halter Neck Tunic Top',
    price: 1399,
    originalPrice: 2499,
    discountPercentage: 44,
    gender: 'women',
    category: 'top',
    subCategory: 'tunics',
    images: ['/assets/real/lookbook_women_6_nee.webp'],
    thumbnail: '/assets/real/lookbook_women_6_nee.webp',
    description: 'Artisanal indigo block-printed halter top featuring subtle tie-back detailing and natural breathable organic cotton.',
    fabric: '100% Organic Cotton',
    fit: 'Relaxed Fit',
    rating: 4.9,
    reviewsCount: 142,
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'New Collection',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-tp-4',
    brand: 'Sassafras',
    title: 'Vintage Boned Satin Underbust Corset Top - Ivory',
    price: 1199,
    originalPrice: 2299,
    discountPercentage: 48,
    gender: 'women',
    category: 'top',
    subCategory: 'corsets',
    images: ['/assets/real/cat_women_sub_corsets.webp'],
    thumbnail: '/assets/real/cat_women_sub_corsets.webp',
    description: 'Structured corset featuring flexible boning and sweetheart bustier styling with lace-up back eyelets.',
    fabric: 'Duchess Satin',
    fit: 'Structured Corset Fit',
    rating: 4.8,
    reviewsCount: 310,
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Viral Trend',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-tp-5',
    brand: 'Sassafras',
    title: 'Oversized Cloud-Soft Cashmere Blend Knit Sweater',
    price: 1699,
    originalPrice: 2999,
    discountPercentage: 43,
    gender: 'women',
    category: 'top',
    subCategory: 'sweaters',
    images: ['/assets/real/cat_women_sub_sweaters.webp'],
    thumbnail: '/assets/real/cat_women_sub_sweaters.webp',
    description: 'Super-soft drop shoulder knit sweater in creamy vanilla hue featuring chunky ribbed cuffs and hemline.',
    fabric: 'Cashmere Acrylic Blend',
    fit: 'Oversized Slouchy Fit',
    rating: 4.9,
    reviewsCount: 225,
    sizes: ['Free Size'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Winter Warmth',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-tp-6',
    brand: 'The Souled Store',
    title: 'Lilac Pastel Crew-Neck Fitted Cotton Baby Tee',
    price: 599,
    originalPrice: 999,
    discountPercentage: 40,
    gender: 'women',
    category: 'top',
    subCategory: 't-shirts',
    images: ['/assets/real/cat_women_top_card.png'],
    thumbnail: '/assets/real/cat_women_top_card.png',
    description: 'Everyday 90s baby tee cut in super-combed cotton with subtle ribbed neckline and cropped waist length.',
    fabric: '100% Combed Cotton',
    fit: 'Fitted Baby Tee',
    rating: 4.7,
    reviewsCount: 480,
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Daily Fit',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },

  // --- BOTTOM WEAR ---
  {
    id: 'w-bt-1',
    brand: 'Tilt',
    title: 'Butter Soft Bamboo Wide-Leg High-Waist Relaxed Trousers',
    price: 1499,
    originalPrice: 2499,
    discountPercentage: 40,
    gender: 'women',
    category: 'bottom',
    subCategory: 'wide leg trousers',
    images: ['/assets/real/lookbook_women_8_tilt.webp'],
    thumbnail: '/assets/real/lookbook_women_8_tilt.webp',
    description: 'Breathable ultra-luxe bamboo cotton relaxed wide-leg trousers designed for effortlessly chic street outings.',
    fabric: 'Bamboo Spandex',
    fit: 'Wide Leg Loose Fit',
    rating: 4.9,
    reviewsCount: 341,
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Bamboo Comfort',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-bt-2',
    brand: 'Sassafras',
    title: 'Ivory Wide-Leg Relaxed High-Waist Denim Trousers',
    price: 1599,
    originalPrice: 2999,
    discountPercentage: 47,
    gender: 'women',
    category: 'bottom',
    subCategory: 'denim jeans',
    images: ['/assets/real/cat_women_bottom_card.png'],
    thumbnail: '/assets/real/cat_women_bottom_card.png',
    description: 'High-rise relaxed fit rigid cotton denim trousers with clean front pockets and full-length wide leg silhouette.',
    fabric: '100% Rigid Cotton Denim',
    fit: 'High-Rise Wide Leg',
    rating: 4.8,
    reviewsCount: 298,
    sizes: ['26', '28', '30', '32'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Trending Fit',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-bt-3',
    brand: 'Tilt',
    title: 'Rose Piped Silk-Satin Relaxed Sleepwear Pyjamas',
    price: 1199,
    originalPrice: 2199,
    discountPercentage: 45,
    gender: 'women',
    category: 'bottom',
    subCategory: 'loungewear',
    images: ['/assets/real/cat_women_sub_pyjamas.webp'],
    thumbnail: '/assets/real/cat_women_sub_pyjamas.webp',
    description: 'Silky smooth drawstring lounge trousers with contrast piping and side pockets for bedtime luxury.',
    fabric: 'Mulberry Satin Poly',
    fit: 'Relaxed Comfort Fit',
    rating: 4.9,
    reviewsCount: 167,
    sizes: ['S', 'M', 'L'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Lounge Luxury',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },

  // --- FOOT WEAR ---
  {
    id: 'w-ft-1',
    brand: 'Sassafras',
    title: 'Nude Strappy Block-Heel Party Sandals',
    price: 1499,
    originalPrice: 2799,
    discountPercentage: 46,
    gender: 'women',
    category: 'footwear',
    subCategory: 'heels',
    images: ['/assets/real/cat_women_footwear_card.png'],
    thumbnail: '/assets/real/cat_women_footwear_card.png',
    description: 'Comfortable 2.5-inch block heel sandals with cushioned footbed and minimal criss-cross ankle straps.',
    fabric: 'Faux Patent Leather',
    fit: 'True to Size',
    rating: 4.8,
    reviewsCount: 310,
    sizes: ['UK 4', 'UK 5', 'UK 6', 'UK 7'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Party Ready',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },

  // --- ACCESSORIES & JEWELLERY ---
  {
    id: 'w-acc-1',
    brand: 'GIVA',
    title: 'Sterling Silver 925 Sparkling Zircon Halo Stud Earrings',
    price: 1199,
    originalPrice: 2199,
    discountPercentage: 45,
    gender: 'women',
    category: 'accessories',
    subCategory: 'fine jewellery',
    images: ['/assets/real/cat_women_sub_jewellery.webp'],
    thumbnail: '/assets/real/cat_women_sub_jewellery.webp',
    description: 'Hypoallergenic authentic 925 sterling silver stud earrings with rhodium anti-tarnish e-coating.',
    fabric: '925 Sterling Silver',
    fit: 'Studs',
    rating: 4.9,
    reviewsCount: 489,
    sizes: ['Free Size'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Certified 925',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  },
  {
    id: 'w-acc-2',
    brand: 'Chumbak',
    title: 'Tropical Paradise Peacock Print Padded Laptop Sleeve & Tote',
    price: 1299,
    originalPrice: 2299,
    discountPercentage: 43,
    gender: 'women',
    category: 'accessories',
    subCategory: 'bags & sleeves',
    images: ['/assets/real/sections/16_chumbak_1.webp'],
    thumbnail: '/assets/real/sections/16_chumbak_1.webp',
    description: 'Quirky signature Chumbak print padded sleeve with vegan leather handles and plush microfiber inner lining.',
    fabric: 'Canvas & Vegan Leather',
    fit: 'Fits Up to 15.6"',
    rating: 4.9,
    reviewsCount: 320,
    sizes: ['Free Size'],
    inStock: true,
    tryAndBuyEligible: true,
    deliveryMinutes: 60,
    deliveryLocation: 'Shreepal Complex, Suren Rd, Mumbai',
    promoTag: 'Quirky Icon',
    couponPromo: 'Coupon: KNOTFESTIVE999'
  }
];

// Put the pureWomenProducts first so women feeds are 100% pure!
const finalProds = [...pureWomenProducts, ...cleanedOtherProds];
console.log('Total Catalog Products:', finalProds.length);
console.log('Total Women Products:', finalProds.filter(p => p.gender === 'women').length);
console.log('Total Men Products:', finalProds.filter(p => p.gender === 'men').length);

const newCode = code.replace(
  /export const PRODUCTS: Product\[\] = \[[\s\S]*?\n\];/,
  'export const PRODUCTS: Product[] = ' + JSON.stringify(finalProds, null, 2) + ';'
);

fs.writeFileSync('data/catalog.ts', newCode, 'utf8');
console.log('Successfully updated data/catalog.ts!');
